const MOJIBAKE_REPLACEMENTS: Array<[RegExp, string]> = [
  [/Ã¡/g, "á"],
  [/Ã /g, "à"],
  [/Ã¢/g, "â"],
  [/Ã£/g, "ã"],
  [/Ã©/g, "é"],
  [/Ãª/g, "ê"],
  [/Ã­/g, "í"],
  [/Ã³/g, "ó"],
  [/Ã´/g, "ô"],
  [/Ãµ/g, "õ"],
  [/Ãº/g, "ú"],
  [/Ã§/g, "ç"],
  [/Ã/g, "Á"],
  [/Ã€/g, "À"],
  [/Ã‚/g, "Â"],
  [/Ãƒ/g, "Ã"],
  [/Ã‰/g, "É"],
  [/ÃŠ/g, "Ê"],
  [/Ã/g, "Í"],
  [/Ã“/g, "Ó"],
  [/Ã”/g, "Ô"],
  [/Ã•/g, "Õ"],
  [/Ãš/g, "Ú"],
  [/Ã‡/g, "Ç"],
  [/Â·/g, "·"],
  [/â€“/g, "-"],
  [/â€”/g, "-"],
  [/â€¦/g, "..."],
  [/ðŸ“š/g, "📚"],
  [/ðŸ‘‹/g, "👋"],
];

const WORD_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bAcademico\b/g, "Acadêmico"],
  [/\bacademico\b/g, "acadêmico"],
  [/\bAcoes\b/g, "Ações"],
  [/\bacoes\b/g, "ações"],
  [/\bAcao\b/g, "Ação"],
  [/\bacao\b/g, "ação"],
  [/\bAcesso configurado\. WhatsApp nao enviado/g, "Acesso configurado. WhatsApp não enviado"],
  [/\bAlteracao\b/g, "Alteração"],
  [/\balteracao\b/g, "alteração"],
  [/\bAprovacao\b/g, "Aprovação"],
  [/\baprovacao\b/g, "aprovação"],
  [/\bArea\b/g, "Área"],
  [/\barea\b/g, "área"],
  [/\bAtencao\b/g, "Atenção"],
  [/\batencao\b/g, "atenção"],
  [/\bAutomatica\b/g, "Automática"],
  [/\bautomatica\b/g, "automática"],
  [/\bAutomatico\b/g, "Automático"],
  [/\bautomatico\b/g, "automático"],
  [/\bAvaliacoes\b/g, "Avaliações"],
  [/\bavaliacoes\b/g, "avaliações"],
  [/\bAvaliacao\b/g, "Avaliação"],
  [/\bavaliacao\b/g, "avaliação"],
  [/\bCapitulo\b/g, "Capítulo"],
  [/\bcapitulo\b/g, "capítulo"],
  [/\bCobranca\b/g, "Cobrança"],
  [/\bcobranca\b/g, "cobrança"],
  [/\bConclusao\b/g, "Conclusão"],
  [/\bconclusao\b/g, "conclusão"],
  [/\bConfiguracoes\b/g, "Configurações"],
  [/\bconfiguracoes\b/g, "configurações"],
  [/\bConteudo\b/g, "Conteúdo"],
  [/\bconteudo\b/g, "conteúdo"],
  [/\bConteudos\b/g, "Conteúdos"],
  [/\bconteudos\b/g, "conteúdos"],
  [/\bCorrecao\b/g, "Correção"],
  [/\bcorrecao\b/g, "correção"],
  [/\bCorrecoes\b/g, "Correções"],
  [/\bcorrecoes\b/g, "correções"],
  [/\bCriterio\b/g, "Critério"],
  [/\bcriterio\b/g, "critério"],
  [/\bDescricao\b/g, "Descrição"],
  [/\bdescricao\b/g, "descrição"],
  [/\bDestinatarios\b/g, "Destinatários"],
  [/\bdestinatarios\b/g, "destinatários"],
  [/\bDisponivel\b/g, "Disponível"],
  [/\bdisponivel\b/g, "disponível"],
  [/\bDuvida\b/g, "Dúvida"],
  [/\bduvida\b/g, "dúvida"],
  [/\bDidatico\b/g, "Didático"],
  [/\bdidatico\b/g, "didático"],
  [/\bE-mail nao enviado/g, "E-mail não enviado"],
  [/\bEmissao\b/g, "Emissão"],
  [/\bemissao\b/g, "emissão"],
  [/\bEntao\b/g, "Então"],
  [/\bentao\b/g, "então"],
  [/\bEstara\b/g, "Estará"],
  [/\bestara\b/g, "estará"],
  [/\bEsta disponivel\b/g, "Está disponível"],
  [/\besta disponivel\b/g, "está disponível"],
  [/\bEsta liberado\b/g, "Está liberado"],
  [/\besta liberado\b/g, "está liberado"],
  [/\bEvolucao\b/g, "Evolução"],
  [/\bevolucao\b/g, "evolução"],
  [/\bFrequencia\b/g, "Frequência"],
  [/\bfrequencia\b/g, "frequência"],
  [/\bGestao\b/g, "Gestão"],
  [/\bgestao\b/g, "gestão"],
  [/\bHistorico\b/g, "Histórico"],
  [/\bhistorico\b/g, "histórico"],
  [/\bInformacao\b/g, "Informação"],
  [/\binformacao\b/g, "informação"],
  [/\bInformacoes\b/g, "Informações"],
  [/\binformacoes\b/g, "informações"],
  [/\bIngles\b/g, "Inglês"],
  [/\bingles\b/g, "inglês"],
  [/\bInstrucao\b/g, "Instrução"],
  [/\binstrucao\b/g, "instrução"],
  [/\bInstrucoes\b/g, "Instruções"],
  [/\binstrucoes\b/g, "instruções"],
  [/\bLancada\b/g, "Lançada"],
  [/\blancada\b/g, "lançada"],
  [/\bLancado\b/g, "Lançado"],
  [/\blancado\b/g, "lançado"],
  [/\bLancamento\b/g, "Lançamento"],
  [/\blancamento\b/g, "lançamento"],
  [/\bLic[aã]o\b/g, "Lição"],
  [/\blic[aã]o\b/g, "lição"],
  [/\bLicoes\b/g, "Lições"],
  [/\blicoes\b/g, "lições"],
  [/\bMateria\b/g, "Matéria"],
  [/\bmateria\b/g, "matéria"],
  [/\bMatematica\b/g, "Matemática"],
  [/\bmatematica\b/g, "matemática"],
  [/\bMatricula\b/g, "Matrícula"],
  [/\bmatricula\b/g, "matrícula"],
  [/\bModulo\b/g, "Módulo"],
  [/\bmodulo\b/g, "módulo"],
  [/\bModulos\b/g, "Módulos"],
  [/\bmodulos\b/g, "módulos"],
  [/\bMultipla\b/g, "Múltipla"],
  [/\bmultipla\b/g, "múltipla"],
  [/\bNao\b/g, "Não"],
  [/\bnao\b/g, "não"],
  [/\bNumero\b/g, "Número"],
  [/\bnumero\b/g, "número"],
  [/\bObrigatorio\b/g, "Obrigatório"],
  [/\bobrigatorio\b/g, "obrigatório"],
  [/\bObrigatorios\b/g, "Obrigatórios"],
  [/\bobrigatorios\b/g, "obrigatórios"],
  [/\bOpcao\b/g, "Opção"],
  [/\bopcao\b/g, "opção"],
  [/\bOpcoes\b/g, "Opções"],
  [/\bopcoes\b/g, "opções"],
  [/\bOrientacao\b/g, "Orientação"],
  [/\borientacao\b/g, "orientação"],
  [/\bOrganizacao\b/g, "Organização"],
  [/\borganizacao\b/g, "organização"],
  [/\bPagina\b/g, "Página"],
  [/\bpagina\b/g, "página"],
  [/\bPaginas\b/g, "Páginas"],
  [/\bpaginas\b/g, "páginas"],
  [/\bPadrao\b/g, "Padrão"],
  [/\bpadrao\b/g, "padrão"],
  [/\bParabens\b/g, "Parabéns"],
  [/\bparabens\b/g, "parabéns"],
  [/\bPermissao\b/g, "Permissão"],
  [/\bpermissao\b/g, "permissão"],
  [/\bPresenca\b/g, "Presença"],
  [/\bpresenca\b/g, "presença"],
  [/\bProximo\b/g, "Próximo"],
  [/\bproximo\b/g, "próximo"],
  [/\bProximos\b/g, "Próximos"],
  [/\bproximos\b/g, "próximos"],
  [/\bQuestao\b/g, "Questão"],
  [/\bquestao\b/g, "questão"],
  [/\bQuestoes\b/g, "Questões"],
  [/\bquestoes\b/g, "questões"],
  [/\bRecebiveis\b/g, "Recebíveis"],
  [/\brecebiveis\b/g, "recebíveis"],
  [/\bReferencia\b/g, "Referência"],
  [/\breferencia\b/g, "referência"],
  [/\bRelatorio\b/g, "Relatório"],
  [/\brelatorio\b/g, "relatório"],
  [/\bRenegociacao\b/g, "Renegociação"],
  [/\brenegociacao\b/g, "renegociação"],
  [/\bReposicao\b/g, "Reposição"],
  [/\breposicao\b/g, "reposição"],
  [/\bSeguranca\b/g, "Segurança"],
  [/\bseguranca\b/g, "segurança"],
  [/\bSera\b/g, "Será"],
  [/\bsera\b/g, "será"],
  [/\bTambem\b/g, "Também"],
  [/\btambem\b/g, "também"],
  [/\bTitulo\b/g, "Título"],
  [/\btitulo\b/g, "título"],
  [/\bUltima\b/g, "Última"],
  [/\bultima\b/g, "última"],
  [/\bUsuario\b/g, "Usuário"],
  [/\busuario\b/g, "usuário"],
  [/\bUsuarios\b/g, "Usuários"],
  [/\busuarios\b/g, "usuários"],
  [/\bVisualizacao\b/g, "Visualização"],
  [/\bvisualizacao\b/g, "visualização"],
  [/\bVoce\b/g, "Você"],
  [/\bvoce\b/g, "você"],
  [/\bate\b/g, "até"],
];

export function polishPortugueseText(value: string) {
  let result = value;
  for (const [pattern, replacement] of MOJIBAKE_REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  for (const [pattern, replacement] of WORD_REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }
  return result;
}
